version: '3'
services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/app
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
    environment:
      YII_ENV: dev
      YII_DEBUG: 1
      DB_DSN: "mysql:host=mysql;port=3306;dbname=bluewindow_brand_toplist"
      DB_USER: root
      DB_PASS: parola123
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: parola123
      MYSQL_DATABASE: bluewindow_brand_toplist
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: